name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Exécutez l'action lors des commits sur la branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 3 : Construisez l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t sekponakokou/chef:latest .

      # Étape 4 : Poussez l'image vers Docker Hub
      - name: Push Docker Image
        run: |
          docker push sekponakokou/chef:latest